### PR TITLE
Add flake.nix

### PR DESCRIPTION
**Pull request by OakleyCord**
This allows people on NixOS to easily use this plugin :)

Heavily referenced from [this](https://github.com/Duckonaut/split-monitor-workspaces/blob/main/flake.nix) project.

### CODE REVIEW

**Comment by VortexCoyote** [comment]
I can't verify that this works, due to me not knowing enough about nix flakes. but since it doesn't break anything with the plugin itself, I will merge!

**Comment by OakleyCord** [comment]
it does work, the only thing is that the install part of this flake may be unconventional but it works

**Comment by nyawox** [comment]
Thanks I was also planning to make same PR around that time:)
Just revisited now and confirmed it can be installed.
It crashes though what version of Hyprland are you using? I tried both from nixos-unstable and latest from upstream flake.

**Comment by OakleyCord** [comment]
> Thanks I was also planning to make same PR around that time:) Just revisited now and confirmed it can be installed. It crashes though what version of Hyprland are you using? I tried both from nixos-unstable and latest from upstream flake.

hi could you elaborate more? (error logs, nix config)

here's how i have it setup:
flake.nix:
```nix
  inputs = {
    ...
    # referencing latest version instead of latest git incase of breaking changes 
    hyprland.url = "github:hyprwm/Hyprland?ref=v0.32.0";
    hyprfocus = {
      url = "github:VortexCoyote/hyprfocus";
      # important!
      inputs.hyprland.follows = "hyprland";
    };
  };
  ...
```
home.nix:
```nix
...
  wayland.windowManager.hyprland = {
    enable = true;
    # important!
    package = inputs.hyprland.packages.${pkgs.system}.hyprland;
    
    plugins = [
      inputs.hyprfocus.packages.${pkgs.system}.default
     ];
  };
...
```
hope this helps :3

**Comment by nyawox** [comment]
I just had to override home-manager hyprland package to the one from hyprland flake thank you

**Pull request merged**
